### ISSUE TITLE
Level 2 torch quest placement issues

### ISSUE THREAD

**Issue by Ezhh** [Cat5TV/tps_skyblock#8]
On level 2, the quest to place torches fails if you place them on the wall, but works if you place them on the floor. 

Both placement options should count toward the quest.

**Comment by shivajiva101** [comment]
added a PR to fix this issue, supports ceiling and wall placement

**Comment by Cat5TV** [comment]
PR Accepted. https://github.com/Cat5TV/tps_skyblock/pull/9
